sudo: required
language: generic

services:
  - docker

#script:
#  - npm run test

script:
  - docker build -t yashjindal28/angular-ems-frontend ./angular-EMS-frontend
  - docker build -t yashjindal28/go-ems-employeeservice ./go-EMS-employeeService
  - docker build -t yashjindal28/go-ems-authservice ./go-EMS-authService
  - docker build -t yashjindal28/go-ems-payrollservice ./go-EMS-payrollService
  - docker build -t yashjindal28/go-ems-departmentservice ./go-EMS-departmentService
  - docker build -t yashjindal28/go-ems-leaveservice ./go-EMS-leaveService
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yashjindal28/angular-ems-frontend
  - docker push yashjindal28/go-ems-employeeservice
  - docker push yashjindal28/go-ems-authservice
  - docker push yashjindal28/go-ems-payrollservice
  - docker push yashjindal28/go-ems-departmentservice
  - docker push yashjindal28/go-ems-leaveservice

