name: deploy-frontend

on:
  push:
    branches: [ "master" ]
    paths:
      - "angular-EMS-frontend/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd angular-EMS-frontend  && docker build -t yashjindal28/angular-ems-frontend . 
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    - run: docker push yashjindal28/angular-ems-frontend